name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --optimize-autoloader --no-dev --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - run: npm install
    - run: npm run production
    - name: Configure application
      run: |
        php artisan key:generate
        php artisan cache:clear
        php artisan config:clear
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

